import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { ClassBlock, Semester, AttendanceSubject } from '../types';
import { semesterGPA } from '../store/cgpaStore';
import { GRADE_POINTS } from '../types';
import {
  attendancePercent, attendanceStatus, classesCanMissSafe, classesNeededForSafe, SAFE_THRESHOLD,
} from '../store/attendanceStore';

export type PdfColorScheme = 'blue' | 'yellow';

// Brand palette used across the PDF exports — matches the app's own
// blue/yellow color scheme so the report you export looks like the theme
// you're currently using.
const BRANDS: Record<PdfColorScheme, {
  accent: [number, number, number];
  onAccent: [number, number, number];
  rowTint: [number, number, number];
  subtitleTint: [number, number, number];
}> = {
  blue: {
    accent: [37, 99, 235],       // #2563EB
    onAccent: [255, 255, 255],
    rowTint: [239, 246, 255],    // #EFF6FF
    subtitleTint: [219, 234, 254],
  },
  yellow: {
    accent: [245, 168, 0],       // #F5A800
    onAccent: [23, 18, 0],       // dark text reads better on yellow
    rowTint: [255, 251, 235],    // #FFFBEB
    subtitleTint: [82, 58, 0],
  },
};

const BRAND_INK: [number, number, number] = [15, 23, 42];
const BRAND_INK_SOFT: [number, number, number] = [100, 116, 139];
const STATUS_RGB: Record<'safe' | 'warning' | 'danger', [number, number, number]> = {
  safe: [23, 178, 106],
  warning: [245, 166, 35],
  danger: [240, 68, 56],
};

function drawHeader(doc: jsPDF, brand: PdfColorScheme, title: string, subtitle: string) {
  const b = BRANDS[brand];
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFillColor(...b.accent);
  doc.rect(0, 0, pageWidth, 34, 'F');
  doc.setTextColor(...b.onAccent);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('Studo', 14, 15);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 14, 24);
  doc.setFontSize(8.5);
  doc.setTextColor(...b.subtitleTint);
  doc.text(subtitle, 14, 30);
  doc.setTextColor(...BRAND_INK);
}

function drawFooter(doc: jsPDF, brand: PdfColorScheme) {
  const b = BRANDS[brand];
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...b.accent);
    doc.setLineWidth(0.6);
    doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);
    doc.setFontSize(8);
    doc.setTextColor(...BRAND_INK_SOFT);
    doc.text('Generated by Studo', 14, pageHeight - 9);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 9, { align: 'right' });
  }
}

export function exportTimetablePdf(classes: ClassBlock[], scheme: PdfColorScheme = 'blue') {
  const b = BRANDS[scheme];
  const doc = new jsPDF();
  drawHeader(doc, scheme, 'Weekly Timetable', `Generated on ${new Date().toLocaleDateString()}`);
  const rows = classes
    .slice()
    .sort((a, b) => a.day.localeCompare(b.day) || a.start.localeCompare(b.start))
    .map((c) => [c.day, `${c.start}–${c.end}`, c.subject, c.faculty, c.room]);
  autoTable(doc, {
    startY: 40,
    head: [['Day', 'Time', 'Subject', 'Faculty', 'Room']],
    body: rows,
    headStyles: { fillColor: b.accent, textColor: b.onAccent, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: b.rowTint },
    styles: { fontSize: 9, cellPadding: 4 },
  });
  drawFooter(doc, scheme);
  doc.save('timetable.pdf');
}

export function exportCgpaPdf(semesters: Semester[], scheme: PdfColorScheme = 'blue') {
  const b = BRANDS[scheme];
  const doc = new jsPDF();
  drawHeader(doc, scheme, 'CGPA Report', `Generated on ${new Date().toLocaleDateString()}`);
  let y = 42;
  semesters.forEach((sem) => {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND_INK);
    doc.text(`${sem.name}  (GPA: ${semesterGPA(sem.subjects).toFixed(2)})`, 14, y);
    autoTable(doc, {
      startY: y + 4,
      head: [['Subject', 'Credits', 'Grade', 'Points']],
      body: sem.subjects.map((s) => [s.name, String(s.credits), s.grade, String(GRADE_POINTS[s.grade])]),
      headStyles: { fillColor: b.accent, textColor: b.onAccent, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: b.rowTint },
      styles: { fontSize: 9, cellPadding: 4 },
      margin: { left: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 12;
  });
  drawFooter(doc, scheme);
  doc.save('cgpa-report.pdf');
}

export function exportAttendancePdf(subjects: AttendanceSubject[], scheme: PdfColorScheme = 'blue') {
  const b = BRANDS[scheme];
  const doc = new jsPDF();
  const overall = subjects.length
    ? subjects.reduce((a, s) => a + attendancePercent(s), 0) / subjects.length
    : 0;
  const overallStatus = attendanceStatus(overall);

  drawHeader(doc, scheme, 'Attendance Report', `Generated on ${new Date().toLocaleDateString()}  ·  Safe threshold: ${SAFE_THRESHOLD}%`);

  // Overall summary card
  const pageWidth = doc.internal.pageSize.getWidth();
  const cardY = 42;
  doc.setDrawColor(...b.accent);
  doc.setLineWidth(0.6);
  doc.roundedRect(14, cardY, pageWidth - 28, 22, 3, 3, 'S');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...BRAND_INK_SOFT);
  doc.text('OVERALL ATTENDANCE', 20, cardY + 8);
  doc.setFontSize(18);
  doc.setTextColor(...STATUS_RGB[overallStatus]);
  doc.text(`${overall.toFixed(1)}%`, 20, cardY + 17);

  doc.setFontSize(9);
  doc.setTextColor(...BRAND_INK_SOFT);
  doc.text('SUBJECTS TRACKED', pageWidth - 90, cardY + 8);
  doc.setFontSize(18);
  doc.setTextColor(...BRAND_INK);
  doc.setFont('helvetica', 'bold');
  doc.text(String(subjects.length), pageWidth - 90, cardY + 17);

  doc.setFontSize(9);
  doc.setTextColor(...BRAND_INK_SOFT);
  doc.setFont('helvetica', 'bold');
  doc.text('STATUS', pageWidth - 45, cardY + 8);
  doc.setFontSize(12);
  doc.setTextColor(...STATUS_RGB[overallStatus]);
  doc.text(overallStatus === 'safe' ? 'Safe' : overallStatus === 'warning' ? 'Warning' : 'Danger', pageWidth - 45, cardY + 17);

  // Per-subject table
  const rows = subjects.map((s) => {
    const pct = attendancePercent(s);
    const status = attendanceStatus(pct);
    const action = pct >= SAFE_THRESHOLD
      ? `Can bunk ${classesCanMissSafe(s)}`
      : `Attend ${classesNeededForSafe(s)} more`;
    return [
      s.name,
      String(s.attended),
      String(s.total),
      `${pct.toFixed(1)}%`,
      status === 'safe' ? 'Safe' : status === 'warning' ? 'Warning' : 'Danger',
      action,
    ];
  });

  autoTable(doc, {
    startY: cardY + 30,
    head: [['Subject', 'Attended', 'Total', 'Attendance', 'Status', `To stay ${SAFE_THRESHOLD}% safe`]],
    body: rows,
    headStyles: { fillColor: b.accent, textColor: b.onAccent, fontStyle: 'bold', halign: 'center' },
    alternateRowStyles: { fillColor: b.rowTint },
    styles: { fontSize: 9, cellPadding: 4, halign: 'center' },
    columnStyles: { 0: { halign: 'left', fontStyle: 'bold' }, 5: { halign: 'left' } },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 4) {
        const label = String(data.cell.raw);
        const rgb = label === 'Safe' ? STATUS_RGB.safe : label === 'Warning' ? STATUS_RGB.warning : STATUS_RGB.danger;
        data.cell.styles.textColor = rgb;
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  drawFooter(doc, scheme);
  doc.save(`attendance-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
